---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(reticulate)

use_condaenv("r-tensorflow")
pd <- import('pandas')
np <- import('numpy')

dytpes <- list(
      'ip'            = 'uint32',
        'app'          = 'uint16',
        'device'        = 'uint16',
        'os'            = 'uint16',
        'channel'       = 'uint16',
        'is_attributed' = 'uint8',
        'click_id'      = 'uint32'
)

train_df = pd$read_csv("../data/adfraud/train_sample.csv", dtype=dytpes, skiprows = range(1, 131886954), usecols=c('ip','app','device','os', 'channel', 'click_time', 'is_attributed')) 

train_df$hour = pd$to_datetime(train_df$click_time) #.dt.hour.astype('uint8')

```


```{python}

train_df$hour = pd  to_datetime(train_df.click_time).dt.hour.astype('uint8')
train_df['day'] = pd.to_datetime(train_df.click_time).dt.day.astype('uint8')
train_df['wday']  = pd.to_datetime(train_df.click_time).dt.dayofweek.astype('uint8')
        
```



